{
 "title": "Wax Node Monitoring",
 "time": { "from": "2023-09-11T23:36:27.556Z", "to": "2023-09-12T11:36:27.556Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(cpu_usage_system, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Blockchain Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "head_block_time_difference_value{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Synced Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "head_block_num_value{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Averages",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load1{host=~\"$host\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "system_load5{host=~\"$host\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "system_load15{host=~\"$host\"}",
     "legendFormat": "10m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpu_usage_system{host=~\"$host\", cpu=\"cpu-total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(mem_used_percent{host=~\"$host\"})",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=~\"$host\",path=\"/\"}",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=~\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_used_percent{host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_used_percent{host=~\"$host\", path=\"/\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Disk Reads/Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(avg by (host)(diskio_read_bytes{host=~\"$host\"}))",
     "legendFormat": "{{ host }} - reads"
    },
    {
     "expr": "rate(avg by (host)(diskio_write_bytes{host=~\"$host\"}))",
     "legendFormat": "{{ host }} - writes"
    }
   ]
  },
  {
   "title": "Packets Sent / Packets Received ( p/s )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate ( avg by (host,interface) (net_packets_sent{host=~\"$host\"}))",
     "legendFormat": "{{host}} - {{ interface }} - sent"
    },
    {
     "expr": "rate ( avg by (host,interface) (net_packets_recv{host=~\"$host\"}))",
     "legendFormat": "{{ host }} - {{ interface }} - received"
    }
   ]
  },
  {
   "title": "Bytes Sent / Bytes Received ( b/s )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate ( avg by (host,interface) (net_bytes_sent{host=~\"$host\"}))",
     "legendFormat": "{{host}} - {{ interface }} - sent"
    },
    {
     "expr": "rate ( avg by (host,interface) (net_bytes_recv{host=~\"$host\"}))",
     "legendFormat": "{{ host }} - {{ interface }} - received"
    }
   ]
  }
 ]
}